function BapunRunArrayWaveformSnippets(neuronID,RatID)
    
    if strcmp(RatID,'N')
        
        neurons       = load('/media/nasko/WD_BLACK/BapunRawMultiArray/RatN/RatN_Day2_2019-10-11_03-58-54.neurons.mat');
        channelsLoop   = 1:128;
        channelShanks = [  ones(16,1); ...
                         2*ones(16,1); ...
                         3*ones(16,1); ...
                         4*ones(16,1); ...
                         5*ones(16,1); ...
                         6*ones(16,1); ...
                         7*ones(16,1); ...
                         8*ones(16,1)];

    elseif strcmp(RatID,'S')
        
        neurons       = load('/media/nasko/WD_BLACK/BapunRawMultiArray/RatS/RatS-Day2NSD-2020-11-27_10-22-29.neurons.mat');
        channelsLoop   = 1:191;
        channelShanks = [  ones(10,1); ...
                         2*ones(11,1); ...
                         3*ones(11,1); ...
                         4*ones(11,1); ...
                         5*ones(11,1); ...
                         6*ones(9,1);  ...
                         7*ones(16,1); ...
                         8*ones(16,1); ...
                         9*ones(16,1); ...
                         10*ones(16,1); ...
                         11*ones(16,1); ...
                         12*ones(16,1); ...
                         13*ones(16,1); ...
                         14*ones(15,1)];
        
    elseif strcmp(RatID,'U')
        
        neurons       = load('/media/nasko/WD_BLACK3/RatU_temp2/RatU_Day2NSD_2021-07-24_08-16-38.neurons.mat');
        channelsLoop   = 1:192;
        channelShanks = [  ones(16,1); ...
                         2*ones(16,1); ...
                         3*ones(16,1); ...
                         4*ones(16,1); ...
                         5*ones(16,1); ...
                         6*ones(16,1);  ...
                         7*ones(16,1); ...
                         8*ones(16,1); ...
                         9*ones(16,1); ...
                         10*ones(16,1); ...
                         11*ones(16,1); ...
                         12*ones(16,1)];
        
    end
        
    %%

    fs         = 30000;
    fpass      = 300;
    
    preLength  = 36;
    postLength = 36;
        
    idx = find(neuronID == (neurons.neuron_ids + 1));
        
    res      = neurons.spiketrains{1,idx};
    shank    = double(neurons.shank_ids(idx)) + 1;
    cellType = neurons.neuron_type(idx,:);

    if strcmp(cellType,'pyr  ')
        cellType = 'p';
    elseif strcmp(cellType,'inter')
        cellType = 'i';
    end

    for j = 1:length(channelsLoop)

        chanDataCell = load(['/media/nasko/WD_BLACK3/RatU_temp/highpassFiltered/ch' num2str(channelsLoop(j)) 'highpass300hz.mat'],'data');
        spikeTimeIndxCell = round(res*fs) + 1;
        [spikeAvgMaxChanCell,waveformsMaxCell] = waveformAvg(double(chanDataCell.data), ... 
                                                             spikeTimeIndxCell, ... 
                                                             preLength,postLength,fpass,fs,false);
        clear chanDataCell1

        data.spikeAvgs     = spikeAvgMaxChanCell;
        data.spikeSnippets = waveformsMaxCell;

        saveStr = ['rat' RatID 'neuron' num2str(neuronID) cellType 'shank' num2str(channelShanks(j)) 'ch' num2str(channelsLoop(j)) '.mat'];       
        save(['/media/nasko/WD_BLACK3/RatU_temp/highpassFiltered/neuronSnippetsPerShank/' saveStr],'data')

    end
            
end