function brainArea = steinmetzBrainArea

    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: /home/nasko/CUNY_Work_NPUltraWaveforms/data/clusters.acronym.tsv
    %
    % Auto-generated by MATLAB on 09-May-2023 21:01:59

    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 10);

    % Specify range and delimiter
    opts.DataLines = [1, Inf];
    opts.Delimiter = "\t";

    % Specify column names and types
    opts.VariableNames = ["acronym", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10"];
    opts.SelectedVariableNames = "acronym";
    opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, ["acronym", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10"], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, ["acronym", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10"], "EmptyFieldRule", "auto");

    % Import the data
    brainArea = readmatrix("/home/nasko/CUNY_Work_NPUltraWaveforms/data/clusters.acronym.tsv", opts);
    brainArea = brainArea(2:end);


    %% Clear temporary variables
    clear opts
    
end