dayNo = '1';

if strcmp(dayNo,'1')
    
    load('/media/nasko/WD_BLACK/UtkuRawMultiArray/AG/AG_2019-12_23_NSD/shank1/merged_2019-Dec-23__05-00-08_18-27-11/merged_2019-Dec-23__05-00-08_18-27-11.TimeIntervalCombined.mat')
    samples = double(ticd(1));
    
    fileDir = '/media/nasko/WD_BLACK/UtkuRawMultiArray/AG/AG_2019-12_23_NSD';
    
    %%
    shank   = 1:6;

    channel = {1:32,33:64,65:96,97:128,129:160,161:192};
    start   = 0;

    % loop shanks
    for i = 1:length(shank)
        % loop channels
        for j = 1:32
            tic

            try 
                data = bz_LoadBinary([fileDir '/shank' num2str(shank(i)) '/MergedRaw.dat'], ...
                                      'samples',      samples, ...
                                      'frequency',    30000, ...
                                      'nChannels',    32, ...
                                      'channels' ,    j);
            catch
                data = bz_LoadBinary([fileDir '/shank' num2str(shank(i)) '/MergedRaw.filtered.dat'], ...
                                      'samples',      samples, ...
                                      'frequency',    30000, ...
                                      'nChannels',    32, ...
                                      'channels' ,    j);
            end
            saveName = ['rawDataCh' num2str(channel{shank(i)}(j)) '.mat'];
            save([fileDir '/shank' num2str(shank(i)) '/' saveName],'data')

            toc
        end
    end
    
elseif strcmp(dayNo,'2')

    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: /media/nasko/1A526DF7526DD851/UtkuRawMultiArray/AG/AG_day1/TimeIntervalCombined.csv
    %
    % Auto-generated by MATLAB on 31-May-2022 15:03:21
    
    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 3);
    
    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";
    
    % Specify column names and types
    opts.VariableNames = ["StartTime", "NumberOfPoints", "SampleRate"];
    opts.VariableTypes = ["datetime", "double", "double"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Specify variable properties
    opts = setvaropts(opts, "StartTime", "InputFormat", "dd-MMM-yyyy HH:mm:ss");
    
    % Import the data
    TimeIntervalCombined = readtable("/media/nasko/WD_BLACK/UtkuRawMultiArray/AG/AG_2019-12_27_NSD/AG_2019-12-27_NSD.TimeIntervalCombined.csv", opts);
    
    
    %% Clear temporary variables
    clear opts
    
    samples = TimeIntervalCombined.NumberOfPoints(1) + ... 
              TimeIntervalCombined.NumberOfPoints(2) + ...
              TimeIntervalCombined.NumberOfPoints(3) + ...
              TimeIntervalCombined.NumberOfPoints(4);
    
    fileDir = '/media/nasko/WD_BLACK/UtkuRawMultiArray/AG/AG_2019-12_27_NSD';
    
    %%
    shank   = 1:6;

    channel = {1:32,33:64,65:96,97:128,129:160,161:192};
    start   = 0;

    % loop shanks
    for i = 1:length(shank)
        % loop channels
        for j = 1:32
            tic

            try 
                data = bz_LoadBinary([fileDir '/shank' num2str(shank(i)) '/MergedRaw.dat'], ...
                                      'samples',      samples, ...
                                      'frequency',    30000, ...
                                      'nChannels',    32, ...
                                      'channels' ,    j);
            catch
                data = bz_LoadBinary([fileDir '/shank' num2str(shank(i)) '/MergedRaw.filtered.dat'], ...
                                      'samples',      samples, ...
                                      'frequency',    30000, ...
                                      'nChannels',    32, ...
                                      'channels' ,    j);
            end
            saveName = ['rawDataCh' num2str(channel{shank(i)}(j)) '.mat'];
            save([fileDir '/shank' num2str(shank(i)) '/' saveName],'data')

            toc
        end
    end
        
end



          
          
          