%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /media/nasko/3ce6d8b6-2570-4c8f-941f-9b4b0641301c/home/nasko/CUNY_Work_Han_Kamran_Utku_dataV2/data/AG_2019-12-23_NSD/AG_2019-12-23_NSD.Probe.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 17-May-2022 23:45:16

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:E257";

% Specify column names and types
opts.VariableNames = ["ChannelNumberComingOutFromProbe", "X", "Y", "Z", "ShankNumber"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
probe = readtable("/media/nasko/3ce6d8b6-2570-4c8f-941f-9b4b0641301c/home/nasko/CUNY_Work_Han_Kamran_Utku_dataV2/data/AG_2019-12-23_NSD/AG_2019-12-23_NSD.Probe.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts


%%

plot(probe.X,probe.Z,'o')
text(probe.X,probe.Z,num2cell(probe.ChannelNumberComingOutFromProbe))