function UtkuWaveformSnippets(dayNo)
    
    randomFlag = true;

    if strcmp(dayNo,'1')
    
        load('/media/nasko/WD_BLACK/UtkuRawMultiArray/AG/AG_2019-12_23_NSD/shank1/merged_2019-Dec-23__05-00-08_18-27-11/merged_2019-Dec-23__05-00-08_18-27-11.TimeIntervalCombined.mat')
        samples = double(ticd(1));

        fileDir     = '/media/nasko/WD_BLACK/UtkuRawMultiArray/AG/AG_2019-12_23_NSD';
        outDatapath = '/media/nasko/WD_BLACK2/UtkuRawDataPerNeuron/AG_2019-12-23_NSD/';
        
        neurons = load('/media/nasko/3ce6d8b6-2570-4c8f-941f-9b4b0641301c/home/nasko/CUNY_Work_Han_Kamran_Utku_dataV2/data/AG_2019-12-23_NSD/AG_2019-12-23_NSD.cell_metrics.cellinfo.mat');

    elseif strcmp(dayNo,'2')

        %% Import data from text file
        % Script for importing data from the following text file:
        %
        %    filename: /media/nasko/1A526DF7526DD851/UtkuRawMultiArray/AG/AG_day1/TimeIntervalCombined.csv
        %
        % Auto-generated by MATLAB on 31-May-2022 15:03:21

        %% Set up the Import Options and import the data
        opts = delimitedTextImportOptions("NumVariables", 3);

        % Specify range and delimiter
        opts.DataLines = [2, Inf];
        opts.Delimiter = ",";

        % Specify column names and types
        opts.VariableNames = ["StartTime", "NumberOfPoints", "SampleRate"];
        opts.VariableTypes = ["datetime", "double", "double"];

        % Specify file level properties
        opts.ExtraColumnsRule = "ignore";
        opts.EmptyLineRule = "read";

        % Specify variable properties
        opts = setvaropts(opts, "StartTime", "InputFormat", "dd-MMM-yyyy HH:mm:ss");

        % Import the data
        TimeIntervalCombined = readtable("/media/nasko/WD_BLACK/UtkuRawMultiArray/AG/AG_2019-12_27_NSD/AG_2019-12-27_NSD.TimeIntervalCombined.csv", opts);


        %% Clear temporary variables
        clear opts

        samples = TimeIntervalCombined.NumberOfPoints(1) + ... 
                  TimeIntervalCombined.NumberOfPoints(2) + ...
                  TimeIntervalCombined.NumberOfPoints(3) + ...
                  TimeIntervalCombined.NumberOfPoints(4);

        fileDir     = '/media/nasko/WD_BLACK/UtkuRawMultiArray/AG/AG_2019-12_27_NSD';
        outDatapath = '/media/nasko/WD_BLACK2/UtkuRawDataPerNeuron/AG_2019-12-27_NSD/';
        
        neurons = load('/media/nasko/3ce6d8b6-2570-4c8f-941f-9b4b0641301c/home/nasko/CUNY_Work_Han_Kamran_Utku_dataV2/data/AG_2019-12-27_NSD/AG_2019-12-27_NSD.cell_metrics.cellinfo.mat');
        
    elseif strcmp(dayNo,'B1')
        
        %% Set up the Import Options and import the data
        opts = delimitedTextImportOptions("NumVariables", 3);

        % Specify range and delimiter
        opts.DataLines = [2, Inf];
        opts.Delimiter = ",";

        % Specify column names and types
        opts.VariableNames = ["StartTime", "NumberOfPoints", "SampleRate"];
        opts.VariableTypes = ["datetime", "double", "double"];

        % Specify file level properties
        opts.ExtraColumnsRule = "ignore";
        opts.EmptyLineRule = "read";

        % Specify variable properties
        opts = setvaropts(opts, "StartTime", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");

        % Import the data
        TimeIntervalCombined = readtable("/media/nasko/3ce6d8b6-2570-4c8f-941f-9b4b0641301c/home/nasko/CUNY_Work_Han_Kamran_Utku_dataV2/data/B1_2022-06-24_NSD_CA1_24hrs/2022-06-24_NSD_CA1_24hrs_TimeIntervalCombined.csv", opts);


        %% Clear temporary variables
        clear opts
        
        samples = sum(TimeIntervalCombined.NumberOfPoints);
        
        fileDir     = '/media/nasko/WD_BLACK/UtkuRawMultiArray/B1';
        outDatapath = '/media/nasko/WD_BLACK2/UtkuRawDataPerNeuron/B1/';
        
    end
    
    halfWidth         = 27;
    numberOfWaveforms = 1000;
    fs                = 30000;
    start             = 0;

    if strcmp(dayNo,'1') || strcmp(dayNo,'2')
        channel           = {1:32,1:32,1:32,1:32,1:32,1:32};
        shank             = 1:6;
    
        % loop neurons
        for unitIdx = 1:length(neurons.cell_metrics.cellID)

            cellType   = neurons.cell_metrics.putativeCellType{unitIdx}; % cell type
    %         cellID   = neurons.cell_metrics.cellID(unitIdx);           % cell ID
            spikeTimes = neurons.cell_metrics.spikes.times{1,unitIdx};   % spike times in seconds
            spikeTimes = spikeTimes*fs;                                  % convert to samples

            % 1000 random spike times
            if randomFlag
               if numberOfWaveforms < length(spikeTimes)
                    spikeTimes = spikeTimes(randperm(length(spikeTimes),numberOfWaveforms));
               end 
            end
            spikeTimes = sort(spikeTimes);

            if strcmp(cellType,'Pyramidal Cell')
                cellType = 'p';
            elseif strcmp(cellType,'Narrow Interneuron')
                cellType = 'i-narrow';
            elseif strcmp(cellType,'Wide Interneuron')
                cellType = 'i-wide';
            end

            % loop shanks
            for channelSetIdx = 1:length(shank)

                waveformSnippetMat = zeros(halfWidth*2,length(channel{channelSetIdx}),length(spikeTimes));

                snippet = struct();

                tic
                parfor i = 1:length(spikeTimes)

                    offset = round(spikeTimes(i) - halfWidth);

                    try 
                        waveformSnippet = bz_LoadBinary([fileDir '/shank' num2str(shank(channelSetIdx)) '/MergedRaw.dat'], ...
                                              'offset',       offset, ... 
                                              'samples',      halfWidth*2, ...
                                              'frequency',    fs, ...
                                              'nChannels',    32, ...
                                              'channels' ,    channel{channelSetIdx});
                    catch
                        waveformSnippet = bz_LoadBinary([fileDir '/shank' num2str(shank(channelSetIdx)) '/MergedRaw.filtered.dat'], ...
                                              'offset',       offset, ... 
                                              'samples',      halfWidth*2, ...
                                              'frequency',    fs, ...
                                              'nChannels',    32, ...
                                              'channels' ,    channel{channelSetIdx});
                    end
                    waveformSnippetMat(:,:,i) = waveformSnippet;

                end
                toc    

                if randomFlag
                    fileName = ['neuron' num2str(neurons.cell_metrics.cellID(unitIdx)) cellType 'Shank' num2str(channelSetIdx) 'random' num2str(numberOfWaveforms) 'spikes'];
                else
                    fileName = ['neuron' num2str(neurons.cell_metrics.cellID(unitIdx)) cellType 'Shank' num2str(channelSetIdx)];
                end

                snippet.waveformSnippetMat = waveformSnippetMat;
                snippet.spikeTimes         = spikeTimes;

                save([outDatapath fileName],'snippet')
            end

            disp([num2str(100*round(unitIdx/length(neurons.cell_metrics.cellID),4)) '% done'])

        end
        
    elseif strcmp(dayNo,'B1')
        
        channel           = {1:32,    ...
                             33:64,   ...
                             65:96,   ...
                             97:128,  ...
                             129:160, ...
                             161:192, ...
                             193:224, ...
                             225:256};
        shank             = 1:8;
        
        UtkuPath         = '/media/nasko/3ce6d8b6-2570-4c8f-941f-9b4b0641301c/home/nasko/CUNY_Work_Han_Kamran_Utku_dataV2/data/';
        datapath         = [UtkuPath 'B1_2022-06-24_NSD_CA1_24hrs/2022-06-24_NSD_CA1_24hrs/2022-06-24_NSD_CA1_24hrscrs-merged_cleaned.GUI' '/'];
        spikeTimesAll    = double(readNPY([datapath 'spike_times.npy']))/fs;
        spikeIndAll      = double(readNPY([datapath 'spike_clusters.npy']));
        
        neuronList = unique(spikeIndAll);
        
        % loop neurons
        for unitIdx = 1:length(neuronList)
            
            spikeTimes = spikeTimesAll(find(neuronList(unitIdx) == spikeIndAll)) ;   % spike times in seconds
            spikeTimes = spikeTimes*fs;                                              % convert to samples

            % 1000 random spike times
            if randomFlag
               if numberOfWaveforms < length(spikeTimes)
                    spikeTimes = spikeTimes(randperm(length(spikeTimes),numberOfWaveforms));
               end 
            end
            spikeTimes = sort(spikeTimes);
            
            % loop shanks
            for channelSetIdx = 1:length(shank)

                waveformSnippetMat = zeros(halfWidth*2,length(channel{channelSetIdx}),length(spikeTimes));

                snippet = struct();

                tic
                parfor i = 1:length(spikeTimes)

                    offset = round(spikeTimes(i) - halfWidth);

                    waveformSnippet = bz_LoadBinary(['/media/nasko/WD_BLACK/UtkuRawMultiArray/B1' '/' '2022-06-24_NSD_CA1_24hrs.dat'], ...
                                          'offset',       offset, ... 
                                          'samples',      halfWidth*2, ...
                                          'frequency',    fs, ...
                                          'nChannels',    256, ...
                                          'channels' ,    channel{channelSetIdx});

                    waveformSnippetMat(:,:,i) = waveformSnippet;

                end
                toc    

                if randomFlag
                    fileName = ['neuron' num2str(neuronList(unitIdx)) 'Shank' num2str(channelSetIdx) 'random' num2str(numberOfWaveforms) 'spikes'];
                else
                    fileName = ['neuron' num2str(neuronList(unitIdx)) 'Shank' num2str(channelSetIdx)];
                end

                snippet.waveformSnippetMat = waveformSnippetMat;
                snippet.spikeTimes         = spikeTimes;

                save([outDatapath fileName],'snippet')
            end
            
        end
        
    end 
    
end