function unitsCVS = importUnitsCSV 

    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: /media/nasko/WD_BLACK4/ecephys_cache_dir_neuropixel_ipynb/units.csv
    %
    % Auto-generated by MATLAB on 03-Jun-2023 00:19:30

    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 27);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["id", "PT_ratio", "amplitude", "amplitude_cutoff", "cumulative_drift", "d_prime", "duration", "ecephys_channel_id", "epoch_name_quality_metrics", "epoch_name_waveform_metrics", "firing_rate", "halfwidth", "isi_violations", "isolation_distance", "l_ratio", "max_drift", "nn_hit_rate", "nn_miss_rate", "presence_ratio", "quality", "recovery_slope", "repolarization_slope", "silhouette_score", "snr", "spread", "velocity_above", "velocity_below"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, ["epoch_name_quality_metrics", "epoch_name_waveform_metrics", "quality"], "EmptyFieldRule", "auto");

    % Import the data
    unitsCVS = readtable("/media/nasko/WD_BLACK4/ecephys_cache_dir_neuropixel_ipynb/units.csv", opts);
    
end