function probesCVS = importProbesCSV 

    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: /media/nasko/WD_BLACK4/ecephys_cache_dir_neuropixel_ipynb/probes.csv
    %
    % Auto-generated by MATLAB on 03-Jun-2023 11:40:45

    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 10);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["id", "air_channel_index", "ecephys_session_id", "lfp_sampling_rate", "lfp_temporal_subsampling_factor", "name", "phase", "sampling_rate", "surface_channel_index", "has_lfp_data"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "categorical", "double", "double", "double", "categorical"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, ["name", "has_lfp_data"], "EmptyFieldRule", "auto");
    opts = setvaropts(opts, "phase", "TrimNonNumeric", true);
    opts = setvaropts(opts, "phase", "ThousandsSeparator", ",");

    % Import the data
    probesCVS = readtable("/media/nasko/WD_BLACK4/ecephys_cache_dir_neuropixel_ipynb/probes.csv", opts);
    
end