function channelsCVS = importChannelsCSV

    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: /media/nasko/WD_BLACK4/ecephys_cache_dir_neuropixel_ipynb/channels.csv
    %
    % Auto-generated by MATLAB on 03-Jun-2023 11:43:31

    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 10);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["id", "ecephys_probe_id", "local_index", "probe_horizontal_position", "probe_vertical_position", "anterior_posterior_ccf_coordinate", "dorsal_ventral_ccf_coordinate", "left_right_ccf_coordinate", "ecephys_structure_id", "ecephys_structure_acronym"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, "ecephys_structure_acronym", "EmptyFieldRule", "auto");

    % Import the data
    channelsCVS = readtable("/media/nasko/WD_BLACK4/ecephys_cache_dir_neuropixel_ipynb/channels.csv", opts);

end